runtime: nodejs20

handlers:
  # Rute untuk login API
  - url: /login
    script: auto

  # Rute untuk predict API
  - url: /predict
    script: auto

  # Rute untuk diagnoses API
  - url: /diagnoses
    script: auto

  # Rute untuk file statis
  - url: /static
    static_dir: public

  # Fallback untuk semua rute lain (404 handler)
  - url: /.*
    script: auto